name: CI/CD

on:
  push:
    branches: [ main ]
  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码到运行环境
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # 安装项目依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -t mle2mlops .

      # 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 标记并推送 Docker 镜像到 Docker Hub
      - name: Tag and push Docker image
        run: |
          docker tag mle2mlops ${{ secrets.DOCKERHUB_USERNAME }}/mle2mlops:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mle2mlops:latest

      # 模拟部署到生产环境，这里使用 SSH 连接到服务器并拉取新镜像
      # - name: Deploy to production
      #   uses: appleboy/ssh-action@v0.1.14
      #   with:
      #     host: ${{ secrets.PROD_HOST }}
      #     username: ${{ secrets.PROD_USERNAME }}
      #     key: ${{ secrets.PROD_SSH_KEY }}
      #     script: |
      #       docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mle2mlops:latest
      #       docker stop mle2mlops || true
      #       docker rm mle2mlops || true
      #       docker run -d -p 5000:5000 --name mle2mlops ${{ secrets.DOCKERHUB_USERNAME }}/mle2mlops:latest
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mle2mlops:latest
            docker stop mle2mlops || true
            docker run -d -p 5000:5000 --name mle2mlops ${{ secrets.DOCKERHUB_USERNAME }}/mle2mlops:latest



            